#!/bin/bash
# Scan for licenses in current directory
if `which docker > /dev/null`; then
  docker run -v $PWD:/scan -it licensefinder/license_finder /bin/bash -lc "cd /scan && `echo license_finder $@`"
else
  echo "You do not have docker installed. Please install it:"
  echo "    https://docs.docker.com/engine/installation/"
  exit 1
fi
