#!/bin/bash
# Lists all available tags of a specific docker image

BASEURL="https://registry.hub.docker.com/v1/repositories/%IMAGE%/tags"

if [[ -z "$1" ]]; then
    echo "Please provide an imagename as first parameter"
    echo "e.g.: "
    echo "  dockertags circleci/node"
    echo "  dockertags postgres"
    exit 1
fi

URL=$(echo "$BASEURL" | sed "s!%IMAGE%!$1!")

if ! curl "$URL" 2>/dev/null | jq -r ".[].name" 2>/dev/null; then
    echo "Cannot find $1"
fi
