#!/bin/bash
# Open the kubernetes dashboard (if deployed by helm/tiller)
kubectl -n kube-system describe secret $(kubectl get secret -n kube-system | egrep "^kubernetes-dashboard-token" | awk '{print $1}')
export POD_NAME=$(kubectl get pods -n kube-system -l "app=kubernetes-dashboard,release=kubernetes-dashboard" -o jsonpath="{.items[0].metadata.name}")
(sleep 2 && open https://127.0.0.1:8443/)&
kubectl -n kube-system port-forward $POD_NAME 8443:8443
echo https://127.0.0.1:8443/
