#!/bin/bash
# Sets current kube context

CTX=$1

found() {

  printf "Selected: \e[1;31m ${1} \e[0m\n"
  # kubectl config use-context "$1"
  exit 0
}

syntax() {
  echo "kubecontext <CONTEXT>"
  echo
  kubectl config get-contexts
  exit 1
}

[[ -z "$CTX" ]] && syntax

CONTEXT_NAMES=$(kubectl config get-contexts | tail -n +2 | awk '{print $2}')

CONTEXT=$(echo "$CONTEXT_NAMES" | grep "^${CTX}\$")
LINES=$(echo "$CONTEXT_NAMES" | grep "^${CTX}\$" -c)

[[ "$LINES" -eq "1" ]] && found "$CONTEXT"

CONTEXT=$(echo "$CONTEXT_NAMES" | grep "${CTX}")
LINES=$(echo "$CONTEXT_NAMES" | grep "${CTX}" -c)

[[ "$LINES" -eq "1" ]] && found "$CONTEXT"

echo "Too many matches, please refine: $CTX"
exit 1
