#!/bin/bash
# Start portainer
docker rm --force portainer
docker run --restart always --name portainer -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer:latest --no-auth
