#!/bin/bash
# Returns the path of the most recent Finder window

target=`osascript -e 'tell application "Finder" to if (count of Finder windows) > 0 then get POSIX path of (target of front Finder window as text)'`

echo $target
