#!/bin/bash
# Makes sure all docker containers are stopped before running the docker-compose file

echo "Stopping all running containers"
CONTAINERS=$(docker ps -q)
docker stop $CONTAINERS
docker rm $CONTAINERS

echo "Starting docker-compose"
docker-compose up -d 
docker ps



