#!/bin/bash
# Makes sure all docker containers are stopped before running the docker-compose file

echo "Stopping all running containers"
CONTAINERS=$(docker ps -q)
docker kill $CONTAINERS
docker rm $CONTAINERS
yes | docker volume prune

echo "Starting docker-compose"
docker-compose up -d 


