#!/bin/bash
# Start a webserver in the current directory (optional port as argument)

port=8000
if [[ ! -z "$1" ]]; then
  port=$1
fi

_term() { 
  echo "Caught SIGTERM signal!" 
  kill -TERM "$child" 2>/dev/null
}

trap _term SIGTERM

echo "Doing some initial work...";
python -m http.server $port &

sleep 1

open http://localhost:$port/

child=$! 
wait "$child"