#!/bin/bash
# Update brew

echo brew update | figlet | lolcat
brew update 
echo brew upgrade | figlet | lolcat
brew upgrade 
echo brew cleanup | figlet | lolcat
brew cleanup
echo brew doctor | figlet | lolcat
brew doctor
echo mas upgrade | figlet | lolcat
mas upgrade
echo "pod repo update" | figlet | lolcat
pod repo update
